export type STATETYPE = Array<{
	state: string
	stateCode: string
	districts: Array<string>
}>

export const STATES: STATETYPE = [
	{
		state: "Andhra Pradesh",
		stateCode: "AP",
		districts: [
			"Anantapur",
			"Chittoor",
			"East Godavari",
			"Guntur",
			"Krishna",
			"Kurnool",
			"Nellore",
			"Prakasam",
			"Srikakulam",
			"Visakhapatnam",
			"Vizianagaram",
			"West Godavari",
			"YSR Kadapa",
		],
	},
	{
		districts: [
			"Tawang",
			"West Kameng",
			"East Kameng",
			"Papum Pare",
			"Kurung Kumey",
			"Kra Daadi",
			"Lower Subansiri",
			"Upper Subansiri",
			"West Siang",
			"East Siang",
			"Siang",
			"Upper Siang",
			"Lower Siang",
			"Lower Dibang Valley",
			"Dibang Valley",
			"Anjaw",
			"Lohit",
			"Namsai",
			"Changlang",
			"Tirap",
			"Longding",
		],
		state: "Arunachal Pradesh",
		stateCode: "AR",
	},
	{
		state: "Assam",
		stateCode: "AS",
		districts: [
			"Baksa",
			"Barpeta",
			"Biswanath",
			"Bongaigaon",
			"Cachar",
			"Charaideo",
			"Chirang",
			"Darrang",
			"Dhemaji",
			"Dhubri",
			"Dibrugarh",
			"Goalpara",
			"Golaghat",
			"Hailakandi",
			"Hojai",
			"Jorhat",
			"Kamrup Metropolitan",
			"Kamrup",
			"Karbi Anglong",
			"Karimganj",
			"Kokrajhar",
			"Lakhimpur",
			"Majuli",
			"Morigaon",
			"Nagaon",
			"Nalbari",
			"Dima Hasao",
			"Sivasagar",
			"Sonitpur",
			"South Salmara-Mankachar",
			"Tinsukia",
			"Udalguri",
			"West Karbi Anglong",
		],
	},
	{
		districts: [
			"Araria",
			"Arwal",
			"Aurangabad",
			"Banka",
			"Begusarai",
			"Bhagalpur",
			"Bhojpur",
			"Buxar",
			"Darbhanga",
			"East Champaran (Motihari)",
			"Gaya",
			"Gopalganj",
			"Jamui",
			"Jehanabad",
			"Kaimur (Bhabua)",
			"Katihar",
			"Khagaria",
			"Kishanganj",
			"Lakhisarai",
			"Madhepura",
			"Madhubani",
			"Munger (Monghyr)",
			"Muzaffarpur",
			"Nalanda",
			"Nawada",
			"Patna",
			"Purnia (Purnea)",
			"Rohtas",
			"Saharsa",
			"Samastipur",
			"Saran",
			"Sheikhpura",
			"Sheohar",
			"Sitamarhi",
			"Siwan",
			"Supaul",
			"Vaishali",
			"West Champaran",
		],
		state: "Bihar",
		stateCode: "BR",
	},
	{
		districts: ["Chandigarh"],
		state: "Chandigarh (UT)",
		stateCode: "CH",
	},
	{
		districts: [
			"Balod",
			"Baloda Bazar",
			"Balrampur",
			"Bastar",
			"Bemetara",
			"Bijapur",
			"Bilaspur",
			"Dantewada (South Bastar)",
			"Dhamtari",
			"Durg",
			"Gariyaband",
			"Janjgir-Champa",
			"Jashpur",
			"Kabirdham (Kawardha)",
			"Kanker (North Bastar)",
			"Kondagaon",
			"Korba",
			"Korea (Koriya)",
			"Mahasamund",
			"Mungeli",
			"Narayanpur",
			"Raigarh",
			"Raipur",
			"Rajnandgaon",
			"Sukma",
			"Surajpur  ",
			"Surguja",
		],
		stateCode: "CT",
		state: "Chhattisgarh",
	},
	{
		state: "Dadra and Nagar Haveli (UT)",
		districts: ["Dadra & Nagar Haveli"],
		stateCode: "DN",
	},
	{
		districts: ["Daman", "Diu"],
		stateCode: "DD",
		state: "Daman and Diu (UT)",
	},
	{
		stateCode: "DL",
		districts: [
			"Central Delhi",
			"East Delhi",
			"New Delhi",
			"North Delhi",
			"North East  Delhi",
			"North West  Delhi",
			"Shahdara",
			"South Delhi",
			"South East Delhi",
			"South West  Delhi",
			"West Delhi",
		],
		state: "Delhi (NCT)",
	},
	{
		stateCode: "GA",
		state: "Goa",
		districts: ["North Goa", "South Goa"],
	},
	{
		districts: [
			"Ahmedabad",
			"Amreli",
			"Anand",
			"Aravalli",
			"Banaskantha (Palanpur)",
			"Bharuch",
			"Bhavnagar",
			"Botad",
			"Chhota Udepur",
			"Dahod",
			"Dangs (Ahwa)",
			"Devbhoomi Dwarka",
			"Gandhinagar",
			"Gir Somnath",
			"Jamnagar",
			"Junagadh",
			"Kachchh",
			"Kheda (Nadiad)",
			"Mahisagar",
			"Mehsana",
			"Morbi",
			"Narmada (Rajpipla)",
			"Navsari",
			"Panchmahal (Godhra)",
			"Patan",
			"Porbandar",
			"Rajkot",
			"Sabarkantha (Himmatnagar)",
			"Surat",
			"Surendranagar",
			"Tapi (Vyara)",
			"Vadodara",
			"Valsad",
		],
		state: "Gujarat",
		stateCode: "GJ",
	},
	{
		stateCode: "HR",
		state: "Haryana",
		districts: [
			"Ambala",
			"Bhiwani",
			"Charkhi Dadri",
			"Faridabad",
			"Fatehabad",
			"Gurugram (Gurgaon)",
			"Hisar",
			"Jhajjar",
			"Jind",
			"Kaithal",
			"Karnal",
			"Kurukshetra",
			"Mahendragarh",
			"Nuh",
			"Palwal",
			"Panchkula",
			"Panipat",
			"Rewari",
			"Rohtak",
			"Sirsa",
			"Sonipat",
			"Yamunanagar",
		],
	},
	{
		state: "Himachal Pradesh",
		stateCode: "HP",
		districts: [
			"Bilaspur",
			"Chamba",
			"Hamirpur",
			"Kangra",
			"Kinnaur",
			"Kullu",
			"Lahaul & Spiti",
			"Mandi",
			"Shimla",
			"Sirmaur (Sirmour)",
			"Solan",
			"Una",
		],
	},
	{
		districts: [
			"Bokaro",
			"Chatra",
			"Deoghar",
			"Dhanbad",
			"Dumka",
			"East Singhbhum (Jamshedpur)",
			"Garhwa",
			"Giridih",
			"Godda",
			"Gumla",
			"Hazaribagh",
			"Jamtara",
			"Khunti",
			"Koderma",
			"Latehar",
			"Lohardaga",
			"Pakur",
			"Palamu",
			"Ramgarh",
			"Ranchi",
			"Sahibganj",
			"Seraikela-Kharsawan",
			"Simdega",
			"West Singhbhum (Chaibasa)",
		],
		state: "Jharkhand",
		stateCode: "JH",
	},
	{
		state: "Karnataka",
		districts: [
			"Bagalkot",
			"Ballari (Bellary)",
			"Belagavi (Belgaum)",
			"Bangalore",
			"Bidar",
			"Chamarajanagar",
			"Chikballapur",
			"Chikkamagaluru (Chikmagalur)",
			"Chitradurga",
			"Dakshina Kannada",
			"Davangere",
			"Dharwad",
			"Gadag",
			"Hassan",
			"Haveri",
			"Kalaburagi (Gulbarga)",
			"Kodagu",
			"Kolar",
			"Koppal",
			"Mandya",
			"Mysuru (Mysore)",
			"Raichur",
			"Ramanagara",
			"Shivamogga (Shimoga)",
			"Tumakuru (Tumkur)",
			"Udupi",
			"Uttara Kannada (Karwar)",
			"Vijayapura (Bijapur)",
			"Yadgir",
		],
		stateCode: "KA",
	},
	{
		districts: [
			"Alappuzha",
			"Ernakulam",
			"Idukki",
			"Kannur",
			"Kasaragod",
			"Kollam",
			"Kottayam",
			"Kozhikode",
			"Malappuram",
			"Palakkad",
			"Pathanamthitta",
			"Thiruvananthapuram",
			"Thrissur",
			"Wayanad",
		],
		state: "Kerala",
		stateCode: "KL",
	},
	{
		stateCode: "LD",
		state: "Lakshadweep (UT)",
		districts: [
			"Agatti",
			"Amini",
			"Androth",
			"Bithra",
			"Chetlat",
			"Kadmath",
			"Kalpeni",
			"Kavaratti",
			"Kiltan",
			"Minicoy",
		],
	},
	{
		stateCode: "MP",
		state: "Madhya Pradesh",
		districts: [
			"Agar Malwa",
			"Alirajpur",
			"Anuppur",
			"Ashoknagar",
			"Balaghat",
			"Barwani",
			"Betul",
			"Bhind",
			"Bhopal",
			"Burhanpur",
			"Chhatarpur",
			"Chhindwara",
			"Damoh",
			"Datia",
			"Dewas",
			"Dhar",
			"Dindori",
			"Guna",
			"Gwalior",
			"Harda",
			"Hoshangabad",
			"Indore",
			"Jabalpur",
			"Jhabua",
			"Katni",
			"Khandwa",
			"Khargone",
			"Mandla",
			"Mandsaur",
			"Morena",
			"Narsinghpur",
			"Neemuch",
			"Panna",
			"Raisen",
			"Rajgarh",
			"Ratlam",
			"Rewa",
			"Sagar",
			"Satna",
			"Sehore",
			"Seoni",
			"Shahdol",
			"Shajapur",
			"Sheopur",
			"Shivpuri",
			"Sidhi",
			"Singrauli",
			"Tikamgarh",
			"Ujjain",
			"Umaria",
			"Vidisha",
		],
	},
	{
		districts: [
			"Ahmednagar",
			"Akola",
			"Amravati",
			"Aurangabad",
			"Beed",
			"Bhandara",
			"Buldhana",
			"Chandrapur",
			"Dhule",
			"Gadchiroli",
			"Gondia",
			"Hingoli",
			"Jalgaon",
			"Jalna",
			"Kolhapur",
			"Latur",
			"Mumbai",
			"Nagpur",
			"Nanded",
			"Nandurbar",
			"Nashik",
			"Osmanabad",
			"Palghar",
			"Parbhani",
			"Pune",
			"Raigad",
			"Ratnagiri",
			"Sangli",
			"Satara",
			"Sindhudurg",
			"Solapur",
			"Thane",
			"Wardha",
			"Washim",
			"Yavatmal",
		],
		state: "Maharashtra",
		stateCode: "MH",
	},
	{
		state: "Manipur",
		districts: [
			"Bishnupur",
			"Chandel",
			"Churachandpur",
			"Imphal East",
			"Imphal West",
			"Jiribam",
			"Kakching",
			"Kamjong",
			"Kangpokpi",
			"Noney",
			"Pherzawl",
			"Senapati",
			"Tamenglong",
			"Tengnoupal",
			"Thoubal",
			"Ukhrul",
		],
		stateCode: "MN",
	},
	{
		districts: [
			"East Garo Hills",
			"East Jaintia Hills",
			"East Khasi Hills",
			"North Garo Hills",
			"Ri Bhoi",
			"South Garo Hills",
			"South West Garo Hills",
			"South West Khasi Hills",
			"West Garo Hills",
			"West Jaintia Hills",
			"West Khasi Hills",
		],
		stateCode: "ML",
		state: "Meghalaya",
	},
	{
		state: "Mizoram",
		stateCode: "MZ",
		districts: [
			"Aizawl",
			"Champhai",
			"Kolasib",
			"Lawngtlai",
			"Lunglei",
			"Mamit",
			"Saiha",
			"Serchhip",
		],
	},
	{
		stateCode: "NL",
		districts: [
			"Dimapur",
			"Kiphire",
			"Kohima",
			"Longleng",
			"Mokokchung",
			"Mon",
			"Peren",
			"Phek",
			"Tuensang",
			"Wokha",
			"Zunheboto",
		],
		state: "Nagaland",
	},
	{
		districts: [
			"Angul",
			"Balangir",
			"Balasore",
			"Bargarh",
			"Bhadrak",
			"Boudh",
			"Cuttack",
			"Deogarh",
			"Dhenkanal",
			"Gajapati",
			"Ganjam",
			"Jagatsinghapur",
			"Jajpur",
			"Jharsuguda",
			"Kalahandi",
			"Kandhamal",
			"Kendrapara",
			"Kendujhar (Keonjhar)",
			"Khordha",
			"Koraput",
			"Malkangiri",
			"Mayurbhanj",
			"Nabarangpur",
			"Nayagarh",
			"Nuapada",
			"Puri",
			"Rayagada",
			"Sambalpur",
			"Subarnapur (Sonepur)",
			"Sundargarh",
		],
		stateCode: "OD",
		state: "Odisha",
	},
	{
		stateCode: "PY",
		districts: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
		state: "Puducherry (UT)",
	},
	{
		state: "Punjab",
		stateCode: "PB",
		districts: [
			"Amritsar",
			"Barnala",
			"Bathinda",
			"Faridkot",
			"Fatehgarh Sahib",
			"Fazilka",
			"Ferozepur",
			"Gurdaspur",
			"Hoshiarpur",
			"Jalandhar",
			"Kapurthala",
			"Ludhiana",
			"Mansa",
			"Moga",
			"Muktsar",
			"Nawanshahr (Shahid Bhagat Singh Nagar)",
			"Pathankot",
			"Patiala",
			"Rupnagar",
			"Sahibzada Ajit Singh Nagar (Mohali)",
			"Sangrur",
			"Tarn Taran",
		],
	},
	{
		state: "Rajasthan",
		districts: [
			"Ajmer",
			"Alwar",
			"Banswara",
			"Baran",
			"Barmer",
			"Bharatpur",
			"Bhilwara",
			"Bikaner",
			"Bundi",
			"Chittorgarh",
			"Churu",
			"Dausa",
			"Dholpur",
			"Dungarpur",
			"Hanumangarh",
			"Jaipur",
			"Jaisalmer",
			"Jalore",
			"Jhalawar",
			"Jhunjhunu",
			"Jodhpur",
			"Karauli",
			"Kota",
			"Nagaur",
			"Pali",
			"Pratapgarh",
			"Rajsamand",
			"Sawai Madhopur",
			"Sikar",
			"Sirohi",
			"Sri Ganganagar",
			"Tonk",
			"Udaipur",
		],
		stateCode: "RJ",
	},
	{
		state: "Sikkim",
		districts: [
			"East Sikkim",
			"North Sikkim",
			"South Sikkim",
			"West Sikkim",
		],
		stateCode: "SK",
	},
	{
		districts: [
			"Ariyalur",
			"Chengalpattu",
			"Chennai",
			"Coimbatore",
			"Cuddalore",
			"Dharmapuri",
			"Dindigul",
			"Erode",
			"Kallakurichi",
			"Kanchipuram",
			"Kanyakumari",
			"Karur",
			"Krishnagiri",
			"Madurai",
			"Nagapattinam",
			"Namakkal",
			"Nilgiris",
			"Perambalur",
			"Pudukkottai",
			"Ramanathapuram",
			"Ranipet",
			"Salem",
			"Sivaganga",
			"Tenkasi",
			"Thanjavur",
			"Theni",
			"Thoothukudi",
			"Tiruchirappalli",
			"Tirunelveli",
			"Tirupathur",
			"Tiruppur",
			"Tiruvallur",
			"Tiruvannamalai",
			"Tiruvarur",
			"Vellore",
			"Viluppuram",
			"Virudhunagar",
		],
		stateCode: "TN",
		state: "Tamil Nadu",
	},
	{
		districts: [
			"Adilabad",
			"Bhadradri Kothagudem",
			"Hyderabad",
			"Jagtial",
			"Jangaon",
			"Jayashankar Bhupalpally",
			"Jogulamba Gadwal",
			"Kamareddy",
			"Karimnagar",
			"Khammam",
			"Kumuram Bheem Asifabad",
			"Mahabubabad",
			"Mahabubnagar",
			"Mancherial",
			"Medak",
			"Medchal-Malkajgiri",
			"Nagarkurnool",
			"Nalgonda",
			"Nirmal",
			"Nizamabad",
			"Peddapalli",
			"Rajanna Sircilla",
			"Rangareddy",
			"Sangareddy",
			"Siddipet",
			"Suryapet",
			"Vikarabad",
			"Wanaparthy",
			"Warangal (Rural)",
			"Warangal (Urban)",
			"Yadadri Bhuvanagiri",
		],
		stateCode: "TS",
		state: "Telangana",
	},
	{
		stateCode: "TR",
		districts: [
			"Dhalai",
			"Gomati",
			"Khowai",
			"North Tripura",
			"Sepahijala",
			"South Tripura",
			"Unakoti",
			"West Tripura",
		],
		state: "Tripura",
	},
	{
		state: "Uttar Pradesh",
		stateCode: "UP",
		districts: [
			"Agra",
			"Aligarh",
			"Ambedkar Nagar",
			"Amethi (Chatrapati Sahuji Mahraj Nagar)",
			"Amroha (J.P. Nagar)",
			"Auraiya",
			"Ayodhya (Faizabad)",
			"Azamgarh",
			"Baghpat",
			"Bahraich",
			"Ballia",
			"Balrampur",
			"Banda",
			"Barabanki",
			"Bareilly",
			"Basti",
			"Bhadohi",
			"Bijnor",
			"Budaun",
			"Bulandshahr",
			"Chandauli",
			"Chitrakoot",
			"Deoria",
			"Etah",
			"Etawah",
			"Farrukhabad",
			"Fatehpur",
			"Firozabad",
			"Gautam Buddha Nagar",
			"Ghaziabad",
			"Ghazipur",
			"Gonda",
			"Gorakhpur",
			"Hamirpur",
			"Hapur (Panchsheel Nagar)",
			"Hardoi",
			"Hathras",
			"Jalaun",
			"Jaunpur",
			"Jhansi",
			"Kannauj",
			"Kanpur Dehat",
			"Kanpur Nagar",
			"Kasganj",
			"Kaushambi",
			"Kheri",
			"Kushinagar",
			"Lalitpur",
			"Lucknow",
			"Maharajganj",
			"Mahoba",
			"Mainpuri",
			"Mathura",
			"Mau",
			"Meerut",
			"Mirzapur",
			"Moradabad",
			"Muzaffarnagar",
			"Pilibhit",
			"Pratapgarh",
			"Prayagraj (Allahabad)",
			"Raebareli",
			"Rampur",
			"Saharanpur",
			"Sambhal (Bhim Nagar)",
			"Sant Kabir Nagar",
			"Shahjahanpur",
			"Shamli",
			"Shravasti",
			"Siddharth Nagar",
			"Sitapur",
			"Sonbhadra",
			"Sultanpur",
			"Unnao",
			"Varanasi",
		],
	},
	{
		stateCode: "UT",
		districts: [
			"Almora",
			"Bageshwar",
			"Chamoli",
			"Champawat",
			"Dehradun",
			"Haridwar",
			"Nainital",
			"Pauri Garhwal",
			"Pithoragarh",
			"Rudraprayag",
			"Tehri Garhwal",
			"Udham Singh Nagar",
			"Uttarkashi",
		],
		state: "Uttarakhand",
	},
	{
		districts: [
			"Alipurduar",
			"Bankura",
			"Birbhum",
			"Cooch Behar",
			"Dakshin Dinajpur (South Dinajpur)",
			"Darjeeling",
			"Hooghly",
			"Howrah",
			"Jalpaiguri",
			"Jhargram",
			"Kalimpong",
			"Kolkata",
			"Malda",
			"Murshidabad",
			"Nadia",
			"North 24 Parganas",
			"Paschim Medinipur (West Medinipur)",
			"Purba Medinipur (East Medinipur)",
			"Purulia",
			"South 24 Parganas",
			"Uttar Dinajpur (North Dinajpur)",
		],
		stateCode: "WB",
		state: "West Bengal",
	},
]
